### ISSUE TITLE
Error when I create a command

### ISSUE THREAD

**Issue by Bosseur31** [raman325/broadlink-rm-rest#8]
Hello 

When I launch the request to register an IR command, an error appears. The blasters still go into receive mode and seem to receive the IR code but the response to the request is INTERNAL SERVER ERROR. I specify that the error appears before the blasters has received the IR code and that the INTERNAL SERVER ERROR appears when the blaster seems to receive the IR code.

`[2021-02-08 16:44:48 +0100] [1887] [ERROR] Error handling request /targets/yahama/commands/test?blaster_attr=ip&blaster_value=192.168.31.83
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.7/dist-packages/falcon/api.py", line 269, in __call__
    responder(req, resp, **params)
  File "/home/pi/broadlink-rm-rest/app/app.py", line 294, in on_put
    value = blaster.get_command()
  File "/home/pi/broadlink-rm-rest/app/db_helpers/blaster_db.py", line 95, in get_command
    value = device.check_data()
  File "/usr/local/lib/python3.7/dist-packages/broadlink/remote.py", line 26, in check_data
    return self._send(0x4)
  File "/usr/local/lib/python3.7/dist-packages/broadlink/remote.py", line 20, in _send
    check_error(resp[0x22:0x24])
  File "/usr/local/lib/python3.7/dist-packages/broadlink/exceptions.py", line 137, in check_error
    raise exception(error_code)
broadlink.exceptions.ReadError: [Errno -10] Read error
`

Thanks you for your times.

**Comment by raman325** [comment]
Hi, it appears the error is occurring upstream (in the broadlink package). I currently have broadlink pinned, I can see if there's a later version that we can move to that will hopefully resolve this issue

**Comment by Bosseur31** [comment]
Yes the version 0.16.0 has been published, the upgrade is difficult? I can be part of the integration.

**Comment by Bosseur31** [comment]
I tested with last update of python-broadlink and it works in python no error.

**Comment by raman325** [comment]
Just bumped the version, thanks!

**Comment by Bosseur31** [comment]
This Error do not change...

`[2021-02-09 18:04:08 +0100] [3920] [ERROR] Error handling request /targets/yahama/commands/test?blaster_attr=ip&blaster_value=192.168.31.83
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.7/dist-packages/falcon/api.py", line 269, in __call__
    responder(req, resp, **params)
  File "/home/pi/broadlink-rm-rest/app/app.py", line 294, in on_put
    value = blaster.get_command()
  File "/home/pi/broadlink-rm-rest/app/db_helpers/blaster_db.py", line 95, in get_command
    value = device.check_data()
  File "/usr/local/lib/python3.7/dist-packages/broadlink/remote.py", line 21, in check_data
    check_error(response[0x22:0x24])
  File "/usr/local/lib/python3.7/dist-packages/broadlink/exceptions.py", line 137, in check_error
    raise exception(error_code)
broadlink.exceptions.ReadError: [Errno -10] Read error
`

**Comment by Bosseur31** [comment]
Hi after some research on the error, I see that : ReadError means you are trying to read an empty buffer.
You have an idea ?

**Comment by raman325** [comment]
That likely means that the library is timing out waiting for a signal to be read. Make sure when you press the key on your remote that you are within listening range of the device

**Comment by Bosseur31** [comment]
Yes absolutly, because with python-broadlink CLI the command is well learned... I do not understand.
I just realized that the endpoint returns internal server error before I send the command, there is a delay of 2 or 3 seconds maximum, the timeout is however longer ...

**Comment by raman325** [comment]
I just pushed a fix to avoid the exception, but the error is still being thrown by the `broadlink` library. What command are you using with the CLI that is working? I can check the logic that's being used there to see if maybe the way I need to handle it has changed.

**Comment by raman325** [comment]
Nevermind, I found it. Try with the latest and let me know what happens.

**Comment by Coday-meric** [comment]
Oh amazing, I see tomorow and make à feedback

**Comment by raman325** [comment]
To be clear, I just pulled some of the logic that exists in `python-broadlink` into my code, but can't guarantee it will resolve the issue

**Comment by Coday-meric** [comment]
It works great, thank you for your work.
